"""Render docker-compose.yml from nodes.json.

    python3 gen_compose.py                 # nodes.json -> docker-compose.yml
    python3 gen_compose.py --workers 8     # ignore nodes.json; N identical default workers
    python3 gen_compose.py --stdout        # print instead of writing

nodes.json is a JSON object: each key is a node (container) name, each value is
that node's settings. Every key is optional and falls back to DEFAULTS below.
The coordinator is NOT a node; it runs on the host and workers reach it at
COORDINATOR_URL.

Per-node knobs:
  cpus            CPU quota for the container (0.25 = a quarter core). Simulates machine speed.
  mem_limit       Memory cap, e.g. "1g".
  torch_threads   PyTorch intra-op threads. Default ceil(cpus), so a capped container
                  does not oversubscribe its quota.
  latency_ms      Added delay on the worker's OUTBOUND path (tc netem). Measured RTT ~= this.
  jitter_ms       Random +/- variation on latency_ms.
  bandwidth_mbit  Cap on the worker's UPLOAD rate. 0 = unlimited. Home uplink is the real
                  bottleneck for volunteers, so shaping egress is the one that matters.
  loss_pct        Random packet loss on the outbound path, in percent. Use deliberately:
                  TCP throughput ~ MSS / (RTT * sqrt(loss)), so 0.5% loss at 200 ms RTT caps
                  a flow near 1 Mbit/s regardless of bandwidth_mbit (measured: 0.9 Mbit/s).
  dtype           "float32" | "bfloat16". Simulates chips that compute slightly different numbers.
  malicious       true -> worker sends garbage deltas (PRD 7.11 stretch). Ignored until implemented.
  join_delay_s    Seconds to wait before starting work. Simulates a late joiner.
  speed_hint      Free-text tag reported at registration; for logs and plots only.
  restart         Docker restart policy: "no" | "on-failure" | "unless-stopped".

Shaping is applied inside the container by entrypoint.sh, which needs NET_ADMIN
(added automatically).
"""
from __future__ import annotations

import argparse
import ipaddress
import json
import math

import yaml

# ---- global settings (not per-node) -----------------------------------------
COORDINATOR_URL = "http://host.docker.internal:8000"   # host-side coordinator, reachable from every container
NETWORK_NAME = "lan"
SUBNET = "172.28.0.0/16"
FIRST_IP = "172.28.0.11"                               # workers get consecutive static IPs from here
IMAGE_NAME = "decentralized-gpt-worker"
NODE_PORT = 8001                                       # reserved for node.py (plumbing check); unused by worker.py
COMMAND = ["python3", "worker.py"]                     # what each container runs; ["python3", "node.py"] = plumbing check

DEFAULTS = {
    "cpus": 1.0,
    "mem_limit": "1g",
    "torch_threads": None,
    "latency_ms": 0,
    "jitter_ms": 0,
    "bandwidth_mbit": 0,
    "loss_pct": 0,
    "dtype": "float32",
    "malicious": False,
    "join_delay_s": 0,
    "speed_hint": "",
    "restart": "no",
}

HEADER = "# GENERATED by gen_compose.py from nodes.json -- edit nodes.json, not this file.\n"


def load_nodes(path: str) -> dict[str, dict]:
    with open(path) as f:
        nodes = json.load(f)
    if not isinstance(nodes, dict) or not nodes:
        raise SystemExit(f"{path}: expected a non-empty JSON object of {{name: settings}}")
    for name, cfg in nodes.items():
        if not isinstance(cfg, dict):
            raise SystemExit(f"{path}: node {name!r} must be an object")
        unknown = set(cfg) - set(DEFAULTS)
        if unknown:
            raise SystemExit(f"{path}: node {name!r} has unknown keys {sorted(unknown)}")
    return nodes


def render(nodes: dict[str, dict], coordinator_url: str = COORDINATOR_URL) -> str:
    ip0 = ipaddress.ip_address(FIRST_IP)
    services = {}
    for i, (name, cfg) in enumerate(nodes.items()):
        node = {**DEFAULTS, **cfg}
        cpus = float(node["cpus"])
        threads = int(node["torch_threads"] or max(1, math.ceil(cpus)))
        ip = str(ip0 + i)
        env = {
            "NODE_NAME": name,
            "NODE_ROLE": "worker",
            "NODE_IP": ip,
            "NODE_PORT": str(NODE_PORT),
            "COORDINATOR_URL": coordinator_url,
            "CPUS": str(cpus),
            "TORCH_THREADS": str(threads),
            "OMP_NUM_THREADS": str(threads),
            "MKL_NUM_THREADS": str(threads),
            "NET_LATENCY_MS": str(node["latency_ms"]),
            "NET_JITTER_MS": str(node["jitter_ms"]),
            "NET_BANDWIDTH_MBIT": str(node["bandwidth_mbit"]),
            "NET_LOSS_PCT": str(node["loss_pct"]),
            "DTYPE": str(node["dtype"]),
            "MALICIOUS": "1" if node["malicious"] else "0",
            "JOIN_DELAY_S": str(node["join_delay_s"]),
            "SPEED_HINT": str(node["speed_hint"]),
            "PYTHONUNBUFFERED": "1",
        }
        services[name] = {
            "image": IMAGE_NAME,
            # only the first service builds; the rest reuse the image (avoids N parallel builds racing)
            **({"build": {"context": ".", "dockerfile": "Dockerfile"}} if i == 0 else {}),
            "container_name": name,
            "hostname": name,
            "cpus": cpus,
            "mem_limit": str(node["mem_limit"]),
            "cap_add": ["NET_ADMIN"],
            "environment": env,
            "volumes": ["./:/app"],                    # live code + data + results; no rebuild on edit
            "networks": {NETWORK_NAME: {"ipv4_address": ip}},
            "extra_hosts": ["host.docker.internal:host-gateway"],   # Linux hosts; harmless on Docker Desktop
            "restart": str(node["restart"]),
            "command": COMMAND,
        }
    doc = {
        "name": "decentralized-gpt",
        "services": services,
        "networks": {NETWORK_NAME: {"driver": "bridge", "ipam": {"config": [{"subnet": SUBNET}]}}},
    }
    return HEADER + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, width=200)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--nodes", default="nodes.json")
    ap.add_argument("--workers", type=int, default=None, help="ignore nodes.json; N identical default workers")
    ap.add_argument("--cpus", type=float, default=None, help="with --workers: CPU quota per worker (default from DEFAULTS)")
    ap.add_argument("--mem", default=None, help="with --workers: memory limit per worker, e.g. 2.5g (default from DEFAULTS)")
    ap.add_argument("--coordinator-url", default=COORDINATOR_URL)
    ap.add_argument("--out", default="docker-compose.yml")
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args()
    if args.workers is not None:
        extra = {"cpus": args.cpus, "speed_hint": f"uniform-{args.cpus:g}cpu"} if args.cpus else {}
        if args.mem:
            extra["mem_limit"] = args.mem
        nodes = {f"worker-{i+1}": dict(extra) for i in range(args.workers)}
    else:
        nodes = load_nodes(args.nodes)
    text = render(nodes, args.coordinator_url)
    if args.stdout:
        print(text)
    else:
        with open(args.out, "w") as f:
            f.write(text)
        print(f"wrote {args.out}: {len(nodes)} worker(s): {', '.join(nodes)}")


if __name__ == "__main__":
    main()
